[package]
name = "burn-hello-world"
version = "0.1.0"
edition = "2024"

[dependencies]
burn = { version = "0.19.1", features = [
    "train",
    "metrics",
    "wgpu",
    "ndarray",
    "autotune",
]}
